### PR TITLE
Fix #17 get code mirror instance with getCodeMirror

### LINKED ISSUE #17: How to get editor instance?
I am migrating from react-codemirror. I would like to know how to get code mirror instance or is it supported?

### PR DESCRIPTION
**Pull request by OsamaShabrez**
Fixes issue #17 returns the editor instance of codemirror for direct access

### CODE REVIEW

**Comment by scniro** [comment]
I'm not seeing where `getCodeMirror` is exposed on the component. When would this be invoked?

**Comment by inoas** [comment]
We have been transitioning from react-codemirror to react-codemirror2 and without this change we cannot access the codemirror instance for the purpose if resize handling.

**Comment by inoas** [comment]
See: https://github.com/JedWatson/react-codemirror/blob/master/src/Codemirror.js#L89-L90

**Comment by scniro** [comment]
@inoas I wouldn't hold your breath much longer to get _any_ PR merged with the original component based on total lack of response from the author as I know you're familiar with. The proposed PR did not expose a public way to do this hence why I closed it.

With that said, I'll happily include this. Can you share a snippet of the API you are currently using to get the instance? I'm trying to identify the best way to write this. I return the instance on about every event so I am curious if you arbitrarily need to get it outside the scope of the events. For example, with using `editorDidMount(editor)` returns the instance. Can you save that in a `var` to use in manipulation when you wish?

Finally my component is not a fork but a complete re-write, so anything you'd like to see just let me know. I'll await your response and get to working on this asap.

**Comment by inoas** [comment]
This is how we use it atm:

In Component
```js
    componentDidMount() {
        const containerElm = document.getElementById(`ReactCodeMirror-${this.props.index}`);
        const handlerElm = document.getElementById(`Codemirror-ResizeHandler-${this.props.index}`);
        codeMirrorResizing(this.codeMirror.getCodeMirror(), containerElm, handlerElm);
    }
```

JSX
```jsx
<div id={`ReactCodeMirror-${index}`}>
    <CodeMirror
        ref={(cm) => { this.codeMirror = cm; }}
        value={filteredTranslation.body}
        name="body"
        onChange={(editor, metadata, value) => {
            this.onChangeCodeMirror(value);
        }}
        options={{
            lineNumbers: true,
            lineWrapping: true,
            mode: codeMirrorMode,
            placeholder: generatePlaceholder(
                dirtyLocaleCount,
                isTranslationFilledElseWhere(cmsElement.cms_elements_translations, 'body'),
                getLabelFromLookup(cmsElementsParsers, cmsElement.parser)
                    + ' - ' + xgettext('BODY_PLACEHOLDER', 'DocumentElementsListItemElement'),
                xgettext('BODY_PLACEHOLDER_WARNING_DISABLE', 'DocumentElementsListItemElement'),
                xgettext('BODY_PLACEHOLDER_WARNING_ENABLE', 'DocumentElementsListItemElement'),
            ),
        }}
        maxLength="65536"
        lang={localeCode}
    />
    <div id={`Codemirror-ResizeHandler-${index}`} className="Codemirror-ResizeHandler" title={gettext('EDITOR_RESIZE_HANDLER_TITLE')} />
</div>
```


### drag + drop & tab-3-state-toggle
```
export function codeMirrorResizing(codeMirror, containerEl, handlerEl) {
    const renderEveryMs = 3; // Set to 40 to save browser CPU
    let startY;
    let startHeight;
    let renderInterval = null;
    let resizeHandlerHeight = 0;
    containerEl.querySelectorAll('.Codemirror-ResizeHandler').forEach((el) => {
        resizeHandlerHeight += getComputedStyle(el).height.replace(/px$/, '');
    });

    codeMirror.setSize(null, CODEMIRROR_MIMIMUM_HEIGHT);

    const onMouseMoveFn = function (e) {
        const newHeight = Math.min(
            window.innerHeight - 100,
            Math.max(CODEMIRROR_MIMIMUM_HEIGHT, ((startHeight + e.y) - startY - resizeHandlerHeight)));
        clearInterval(renderInterval);
        renderInterval = window.setInterval(() => {
            codeMirror.setSize(null, `${newHeight}px`);
            clearInterval(renderInterval);
        }, renderEveryMs);
    };

    const onMouseUpFn = function (e) {
        if (e.target.setCapture) { // Gecko: The good way
            document.releaseCapture();
            document.body.removeEventListener('mousemove', onMouseMoveFn);
        } else { // Blink, Webkit: The bad way
            document.body.removeEventListener('mousemove', onMouseMoveFn, true);
            document.body.classList.remove('Codemirror-ResizeHandler-global-cursor');
        }
        window.removeEventListener('mouseup', onMouseUpFn);
    };

    handlerEl.addEventListener('click', (e) => {
        if (e.y === startY) {
            if (startHeight > CODEMIRROR_MIMIMUM_HEIGHT &&
                startHeight < CODEMIRROR_MEDIUM_HEIGHT) {
                codeMirror.setSize(null, CODEMIRROR_MEDIUM_HEIGHT);
            } else if (startHeight > CODEMIRROR_MEDIUM_HEIGHT &&
                startHeight < CODEMIRROR_AUTO_HEIGHT) {
                codeMirror.setSize(null, CODEMIRROR_AUTO_HEIGHT);
            } else if (startHeight > CODEMIRROR_AUTO_HEIGHT) {
                codeMirror.setSize(null, CODEMIRROR_MIMIMUM_HEIGHT);
            }
        }
    });

    handlerEl.addEventListener('mousedown', (e) => {
        startY = e.y;
        startHeight = parseInt(window.getComputedStyle(containerEl).height.replace(/px$/, ''), 10);

        if (e.target.setCapture) { // Gecko: The good way
            e.target.setCapture();
            document.body.addEventListener('mousemove', onMouseMoveFn);
        } else { // Blink, Webkit: The bad way
            document.body.addEventListener('mousemove', onMouseMoveFn, true);
            document.body.classList.add('Codemirror-ResizeHandler-global-cursor');
        }
        window.addEventListener('mouseup', onMouseUpFn);

        // Stop event: We don't want to select text or html elements, while dragging.
        if (e.stopPropagation) { e.stopPropagation(); }
        if (e.preventDefault) { e.preventDefault(); }
        e.cancelBubble = true; // eslint-disable-line no-param-reassign
        e.returnValue = false; // eslint-disable-line no-param-reassign
        return false;
    });
}
```

**Comment by inoas** [comment]
For now it seems this works:
```jsx
<div id={`ReactCodeMirror-${index}`}>
    <CodeMirror
        value={filteredTranslation.body}
        name="body"
        onChange={(editor, metadata, value) => {
            this.onChangeCodeMirror(value);
        }}
        editorDidMount={(editor) => {
            const containerElm = document.getElementById(`ReactCodeMirror-${index}`);
            const handlerElm = document.getElementById(`Codemirror-ResizeHandler-${index}`);
            codeMirrorResizing(editor, containerElm, handlerElm);
        }}
        options={{
            lineNumbers: true,
            lineWrapping: true,
            mode: codeMirrorMode,
            placeholder: generatePlaceholder(
                dirtyLocaleCount,
                isTranslationFilledElseWhere(cmsElement.cms_elements_translations, 'body'),
                getLabelFromLookup(cmsElementsParsers, cmsElement.parser)
                    + ' - ' + xgettext('BODY_PLACEHOLDER', 'DocumentElementsListItemElement'),
                xgettext('BODY_PLACEHOLDER_WARNING_DISABLE', 'DocumentElementsListItemElement'),
                xgettext('BODY_PLACEHOLDER_WARNING_ENABLE', 'DocumentElementsListItemElement'),
            ),
        }}
        maxLength="65536"
        lang={localeCode}
    />
    <div id={`Codemirror-ResizeHandler-${index}`} className="Codemirror-ResizeHandler" title={gettext('EDITOR_RESIZE_HANDLER_TITLE')} />
</div>
```

**Comment by inoas** [comment]
I think this issue can stay closed. It seems it works for us. In case we got a problem we will report back.

**Comment by scniro** [comment]
@inoas sounds good please reach out should you need anything else! 😎

**Pull request closed without merging**
