### PR TITLE
Export codemirror instance

### PR DESCRIPTION
**Pull request by GabrieleC**
Hi @scniro, I need to invoke a method (registerHelper) on the codemirror object encapsulated in the React component. This PR exports the cm instance to make this possible.

### CODE REVIEW

**Comment by scniro** [comment]
@GabrieleC I am a lot shorter on time these days as when I started this project. Codemirror & React APIs are moving to quickly for me to keep atop of for the day-to-day. I am looking for a co-maintainer of this project. Please contact me directly if you are interested. Thank you for understanding.

**Comment by fongandrew** [comment]
@GabrieleC Just doing some clean up. Is this request still needed? Can you just require codemirror directly and use that? From what I can tell on this PR, it's just re-exporting the exact contents of `require('codemirror')`.

**Comment by GabrieleC** [comment]
> @GabrieleC Just doing some clean up. Is this request still needed? Can you just require codemirror directly and use that? From what I can tell on this PR, it's just re-exporting the exact contents of `require('codemirror')`.

You're right it works, I didn't understand how to use it.

**Comment by elsigh** [comment]
I basically did this ala
```
if (typeof window !== "undefined" && typeof window.navigator !== "undefined") {
  const codemirror = require("codemirror");
  require("codemirror/addon/mode/simple");
  ...
```

**Pull request closed without merging**
