### PR TITLE
Fixes #100 Pass in user defined options to CM constructor in componentDidMount

### LINKED ISSUE #100: Consider providing `userDefinedOptions` in initial mount.
Certain `codemirror` modes (or at least [`graphql`](https://github.com/graphql/codemirror-graphql)) use the initial configuration provided.  However, the props passed to `Controlled` are not applied initially, only in hydration, making it impossible to set those options in that mode.  Would it be possible to pass them in the initial mount?

### PR DESCRIPTION
**Pull request by twheys**
Added second argument to CodeMirror constructor in componentDidMount with the options prop.

### CODE REVIEW

**Comment by Nishchit14** [comment]
This is the perfect solution but incomplete OR :(

**Comment by scniro** [comment]
@twheys @Nishchit14 I am a lot shorter on time these days as when I started this project. Codemirror & React APIs are moving to quickly for me to keep atop of for the day-to-day. I am looking for a co-maintainer of this project. Please contact me directly if you are interested. Thank you for understanding.

**Comment by elsigh** [comment]
@scniro I'm willing to help this PR and help collaborate on this project if you're up for having another maintainer.

**Comment by elsigh** [comment]
@Nishchit14 is this incomplete just for missing a test?

**Comment by elsigh** [comment]
@twheys - any interest in getting this landed?
I think adding a test and ensuring that the code doesn't re-apply options after setting them in the constructor seems good too?
If you're busy I can take this one over.

**Comment by elsigh** [comment]
closing in favor of https://github.com/scniro/react-codemirror2/pull/188

**Pull request closed without merging**
