### PR TITLE
fix: global is not defined (fixes #259)

### LINKED ISSUE #259: global in not defined
https://github.com/scniro/react-codemirror2/blob/3d490109229e8592772db922e9028c9a1dee3336/index.js#L66

this line will cause error in browsers(no webpack bundled). would it be possible to change to:

```js
(typeof global !== 'undefined' && global['PREVENT_CODEMIRROR_RENDER'] === true)
```

### PR DESCRIPTION
**Pull request by aladdin-add**

### CODE REVIEW

**Review by elsigh — APPROVED** [review]

**Comment by aladdin-add** [comment]
@elsigh is there a plan to release a new version?

**Comment by BovineBoy** [comment]
@elsigh is there a plan to release a new version?

**Comment by HansAarneLiblik** [comment]
@elsigh @scniro Any release updates planned ?

**Comment by elsigh** [comment]
I don't think either of us intend to make a release as neither of us are using the project. I don't have the ability to add more committers so I think fork is your best bet.

**Pull request merged**
