### PR TITLE
Updated peer dependency for React 17

### LINKED ISSUE #223: Could not resolve peer dependency for React 17
The latest version of Create React App uses React 17: https://github.com/facebook/create-react-app/releases/tag/v4.0.0

When installing `react-codemirror2` after using the latest version of Create React App, I received an error message regarding the React version from the peer dependencies:

```
$ npm install react-codemirror2 codemirror --save

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: codemirror-test@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@">=15.5 <=16.x" from react-codemirror2@7.2.1
npm ERR! node_modules/react-codemirror2
npm ERR!   react-codemirror2@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/ianhollander/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ianhollander/.npm/_logs/2020-11-17T14_42_25_685Z-debug.log
```

Steps to reproduce: 

```
$ npx create-react-app codemirror-test
$ cd codemirror-test
$ npm install react-codemirror2 codemirror --save
```

I can open a PR to fix.

### PR DESCRIPTION
**Pull request by ihollander**
Fixes #223

### CODE REVIEW

**Comment by Sceurpien** [comment]
Seems ok :D

**Comment by TAO44123** [comment]
> Fixes #223

I try to change the package.json file like you, but no use for  me...

**Comment by bn185069** [comment]
Is anyone able to merge this? This PR has been open since Nov 17 2020

**Comment by skystebnicki** [comment]
Yes please, we are also depending on this merge.

**Comment by bn185069** [comment]
Hey @mattjared or anyone else available, if it's not too much trouble can you merge this PR for us?

**Comment by xCloudzx** [comment]
If anyone still wants this, just install from @ihollander's fork:
`npm install github:ihollander/react-codemirror2`. It's clear this package isn't getting updated anyway.

**Comment by RomanHotsiy** [comment]
Hey @scniro, could you merge this, please? This is a 2 lines PR.

**Comment by abdulrahman-khankan** [comment]
@fongandrew @mattjared @drewswaycool could you please merge this PR if you still have write access? Thank you 🙌

**Review by drewswaycool — APPROVED** [review]

**Comment by drewswaycool** [comment]
> @fongandrew @mattjared @drewswaycool could you please merge this PR if you still have write access? Thank you 🙌 

I don't, sorry 🤷‍♂️.

**Comment by LeifAndersen** [comment]
If anyone cares, I got tired waiting and pushed a version of react-codemirror2 with this patch to npm:

```
npm install @leifandersen/react-codemirror2
```

**Pull request merged**
